package com.sm.util;

public class SQLQueryConstant {
	public static final String INSERT_REGISTER_QUERY="INSERT INTO REGISTER_USER(FIRST_NAME,LAST_NAME,EMAIL,PASSWORD,GENDER,CONTACT_NUMBER,COUNTRY,STATE,CITY,ADDRESS,PIN)VALUES(?,?,?,?,?,?,?,?,?,?,?)";
	
	public static final String INSERT_LOGIN_QUERY="INSERT INTO LOGIN_USER(EMAIL,PASSWORD,REG_ID)VALUES(?,?,?)";

	public static final String LOGIN_QUERY="SELECT REG_ID FROM LOGIN_USER WHERE EMAIL=? AND PASSWORD=?";

    public static final String VIEW_PROFILE_QUERY="SELECT FIRST_NAME,LAST_NAME,EMAIL,GENDER,CONTACT_NUMBER,COUNTRY,STATE,CITY,ADDRESS,PIN FROM REGISTER_USER WHERE REG_ID=?";

    public static final String UPDATE_PROFILE_QUERY="SELECT FIRST_NAME,LAST_NAME,EMAIL,GENDER,CONTACT_NUMBER,COUNTRY,STATE,CITY,ADDRESS,PIN FROM REGISTER_USER WHERE REG_ID=?";

    public static final String UPDATE_USER_INFO_QUERY="UPDATE REGISTER_USER SET FIRST_NAME=?,LAST_NAME=?,EMAIL=?,GENDER=?,CONTACT_NUMBER=?,COUNTRY=?,STATE=?,CITY=?,ADDRESS=?,PIN=? WHERE REG_ID=?";
    
    public static final String UPDATE_LOGIN_INFO_QUERY="UPDATE lOGIN_USER SET EMAIL=? WHERE REG_ID=?";
    
    public static final String GET_REG_ID="SELECT REG_ID FROM REGISTER_USER WHERE EMAIL=?";
    
    public static final String FORGOT_PASSWORD_REGISTER_QUERY="UPDATE REGISTER_USER SET PASSWORD=? WHERE REG_ID=?";
    
    public static final String FORGOT_PASSWORD_LOGIN_QUERY="UPDATE LOGIN_USER SET PASSWORD=? WHERE REG_ID=?";
    
    
}
